module.exports = {
    name: "gemini",
    description: "Gemini AI Simulation",
    execute: async (sock, msg, args) => {
        if (!args.length) return sock.sendMessage(msg.key.remoteJid, { text: "Usage: .gemini <question>" });

        const prompt = args.join(" ");
        // Gemini AI simulated reply
        const reply = `♊ Gemini AI says: "*${prompt}*"\n✨ Thoughtful response generated by Gemini AI simulation.`;
        await sock.sendMessage(msg.key.remoteJid, { text: reply });
    }
}
